import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import localFont from "next/font/local";
import "./globals.css";

export const interVar = localFont({
   src: "../assets/fonts/InterVariable.woff2",
});

export const urbanistVar = localFont({
   src: "../assets/fonts/Urbanist.ttf",
});

const geistSans = Geist({
   variable: "--font-geist-sans",
   subsets: ["latin"],
});

const geistMono = Geist_Mono({
   variable: "--font-geist-mono",
   subsets: ["latin"],
});

export const metadata: Metadata = {
   title: "Create Next App",
   description: "Generated by create next app",
};

export default function RootLayout({
   children,
}: Readonly<{
   children: React.ReactNode;
}>) {
   return (
      <html lang="en" className="">
         <body
            className={`h-screen bg-gray-100 text-slate-700 dark:text-slate-100 dark:bg-[#121212] ${urbanistVar.className}  antialiased`}
         >
            {children}
         </body>
      </html>
   );
}
